"""Self-improving scanner. Walk the collection, find action identifiers that have no
rule in risk_rules.yml yet (the scanner treats those as yellow by default), tally how
often each appears, and write a review file. Capture -> review -> promote: a human then
adds an explicit rule for each, so the safety benchmark gets smarter over time."""
import plistlib
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).parents[1]
RULES = Path(__file__).with_name("risk_rules.yml")


def known_action_ids(rules_path=RULES):
    data = yaml.safe_load(Path(rules_path).read_text())
    return {r["id"] for r in data["rules"]}


def collect_unknown(shortcuts_dir, rules_path=RULES):
    known = known_action_ids(rules_path)
    counts = Counter()
    where = {}
    for plist in sorted(Path(shortcuts_dir).glob("*/shortcut.plist")):
        with open(plist, "rb") as fh:
            doc = plistlib.load(fh)
        for action in doc.get("WFWorkflowActions", []):
            ident = action.get("WFWorkflowActionIdentifier", "")
            if ident and ident not in known:
                counts[ident] += 1
                where.setdefault(ident, set()).add(plist.parent.name)
    return counts, where


def render_report(counts, where):
    lines = [
        "# Unknown actions — review & promote into risk_rules.yml",
        "",
        "These action identifiers appear in the collection but have no rule yet, so the",
        "scanner currently scores them **yellow** by default. Add an explicit rule for each",
        "(tier + weight + reason) to make the safety benchmark smarter. This file is",
        "regenerated by `python -m scripts.learn`.",
        "",
        "| Action | Count | Seen in |",
        "| ------ | :---: | ------- |",
    ]
    if not counts:
        lines.append("| _none — ruleset is caught up_ | 0 | — |")
    for ident, n in counts.most_common():
        lines.append(f"| `{ident}` | {n} | {', '.join(sorted(where[ident]))} |")
    return "\n".join(lines) + "\n"


def main():  # pragma: no cover - filesystem glue
    counts, where = collect_unknown(ROOT / "shortcuts")
    out = ROOT / ".learnings" / "unknown-actions.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text(render_report(counts, where))
    print(f"{len(counts)} unknown action(s) recorded -> {out}")


if __name__ == "__main__":
    main()
